# Generated by Django 6.0.7 on 2026-07-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='مدل')),
                ('year', models.PositiveIntegerField(verbose_name='سال ساخت')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (تومان)')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='کارکرد (کیلومتر)')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('fuel_type', models.CharField(choices=[('petrol', 'بنزینی'), ('diesel', 'دیزلی'), ('hybrid', 'هیبریدی'), ('electric', 'برقی')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'دنده\u200cای'), ('automatic', 'اتوماتیک')], default='automatic', max_length=20)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('main_image', models.ImageField(upload_to='cars/main/', verbose_name='تصویر اصلی')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('sold', 'فروخته شده')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'ماشین',
                'verbose_name_plural': 'ماشین\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cars.car')),
            ],
        ),
    ]
