# Generated by Django 6.0.7 on 2026-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status', 'created_at'], name='cars_car_status_852828_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model_name'], name='cars_car_model_n_76b897_idx'),
        ),
    ]
